# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39cead8deb48278e077ce15c2244adf8ca9e627eed93f8c61b117acd4efa5ece1b9372004cceeba96f24395966e03ca70461581da5e485c0b5f26bbc05ea93ac

test:
  secret_key_base: a7c7f922268d2e88a5132b38fdea4265de29c64446eef6d9242cb3f55714a004cf16b9ad39f9cb5c9bbff794f9c274f2606ba41b5947b3745aef0e13686dbed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
